name: ExtralyCinematic
version: '${version}'
main: pluginsmc.langdua.core.paper.Core
api-version: '1.21'
softdepend: [PlaceholderAPI, WorldGuard, MythicMobs]
commands:
  cinematic:
    description: Main command for ExtralyCinematic
    aliases: [cine]
    permission: cinematic.cmd