name: ExtralyCinematic
version: 0.1-SNAPSHOT
main: pluginsmc.langdua.core.paper.Core
api-version: 1.20
commands:
  cinematic:
    description: Main command for ExtralyCinematic
    permission: extralycinematic.cmd